<a href="https://colab.research.google.com/github/Jonata-Garcia/Operacoes_Matrizes/blob/main/Opera%C3%A7%C3%B5es_Matrizes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##OPERAÇÃO DE MATRIZES

Dada a Matriz A e a Matrz B abaixo, calcule:

1. A soma das duas matrizes *C* = *A* + *B*
2. O produto elemento a elemento *D* = *A* x *B*
3. O produto matricial E = *A* x *B*
4. A Soma de todos os elementos da matriz *C*
5. A transposta da matriz *D*
6. O valor máximo e mínino da matriz *E*

In [1]:
import numpy as np

# Matrizes A e B
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

# 1. Soma das matrizes C = A + B
C = A + B
print("Matriz C (A + B):\n", C)

# 2. Produto elemento a elemento D = A * B
D = A * B
print("Matriz D (A * B elemento a elemento):\n", D)

# 3. Produto matricial E = A @ B
E = np.dot(A, B)
print("Matriz E (A * B produto matricial):\n", E)

# 4. Soma de todos os elementos da matriz C
soma_C = np.sum(C)
print("Soma de todos os elementos de C:", soma_C)

# 5. Transposta da matriz D
D_transposta = D.T
print("Transposta da matriz D:\n", D_transposta)

# 6. Valor máximo e mínimo da matriz E
max_E = np.max(E)
min_E = np.min(E)
print("Valor máximo de E:", max_E)
print("Valor mínimo de E:", min_E)


Matriz C (A + B):
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
Matriz D (A * B elemento a elemento):
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
Matriz E (A * B produto matricial):
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
Soma de todos os elementos de C: 90
Transposta da matriz D:
 [[ 9 24 21]
 [16 25 16]
 [21 24  9]]
Valor máximo de E: 138
Valor mínimo de E: 18
